---

# Treat modifying the docker-compose.yaml file like a black box. It will help keep the main.yml file simpler.

- name: get docker-compose.yaml contents
  ansible.builtin.slurp:
    src: "{{ docker_jfrog_xray_docker_compose_folder }}/docker-compose.yaml"
  register: docker_jfrog_xray_slurp_docker_compose

- name: convert the slurped docker-compose to yaml
  ansible.builtin.set_fact:
    docker_jfrog_xray_docker_compose_yaml: "{{ docker_jfrog_xray_slurp_docker_compose['content'] | b64decode | from_yaml }}"
    docker_jfrog_xray_docker_compose_services_yaml: {}

- name: remove the mongodb service
  ansible.builtin.set_fact:
    docker_jfrog_xray_docker_compose_services_yaml: "{{ docker_jfrog_xray_docker_compose_services_yaml | combine({item.key: item.value})}}"
  when: "{{ item.key not in ['mongodb'] }}"
  with_dict: "{{ docker_jfrog_xray_docker_compose_yaml['services'] }}"

- name: peice together the cleaned docker-compose yaml
  ansible.builtin.set_fact:
    docker_jfrog_xray_docker_compose_yaml_new:
      version: "{{ docker_jfrog_xray_docker_compose_yaml['version'] }}"
      services: "{{ docker_jfrog_xray_docker_compose_services_yaml }}"

- name: write the docker-compose.yaml back out
  ansible.builtin.copy:
    content: "{{ docker_jfrog_xray_docker_compose_yaml_new | to_nice_yaml }}"
    dest: "{{ docker_jfrog_xray_docker_compose_folder }}/docker-compose.yaml"
